# Generated by Django 6.1 on 2026-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_apps', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
